services:

  db:
    image: 'postgres:14-alpine'
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=socialrides
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "8080:5432"